### ISSUE TITLE
website appears to be mis-aligned on desktop

### ISSUE THREAD

**Issue by nonsense** [ethersphere/swarm-home#36]
After the latest update it looks like the website mobile version got fixed, but the desktop version is misaligned. See screenshots that compare the current old version at https://ethswarm.org vs the current master version from github from ethersphere.github.io/swarm-home:

Old:

![Screen Shot 2019-04-01 at 20 22 19](https://user-images.githubusercontent.com/50459/55350232-e50d9180-54bb-11e9-8690-cfdee3b35314.png)

New:

![Screen Shot 2019-04-01 at 20 22 29](https://user-images.githubusercontent.com/50459/55350245-e939af00-54bb-11e9-96d3-1fa70289a357.png)

1. I guess there is a reason why the `Documentation` header link is missing?
2. The logo and the welcome text are not vertically aligned and overall the text looks worse compared to the old version, at least in my taste, maybe other people disagree.

Feel free to close this issue, if you think this is a feature and not a bug.

**Comment by skylenet** [comment]
> 1. I guess there is a reason why the Documentation header link is missing?

Probably because the documentation link is still available at the footer.

**Comment by nonsense** [comment]
> > 1. I guess there is a reason why the Documentation header link is missing?
> 
> Probably because the documentation link is still available at the footer.

True, but Documentation is a big part of Swarm, so there should be a `good` reason for us to remove it from the header in my opinion.

**Comment by skylenet** [comment]
This has been fixed. The only thing missing is a decision on the documentation link.
